name: test and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependency
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: artifact  upload
        uses: actions/upload-artifacts@v3
        with:
          name: dist-artifact
          path: |
            artifact-path
            package.json


